//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V_MyBASEEntities : DbContext
    {
        public V_MyBASEEntities()
            : base("name=V_MyBASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ЗАКАЗЧИКИ> ЗАКАЗЧИКИ { get; set; }
        public virtual DbSet<ЗАКАЗЫ> ЗАКАЗЫ { get; set; }
        public virtual DbSet<ТОВАРЫ> ТОВАРЫ { get; set; }
    }
}
