//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗАКАЗЫ
    {
        public int ID_заказа { get; set; }
        public string Товар { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Адрес { get; set; }
        public string Вид_доставки { get; set; }
        public string Заказчик { get; set; }
    
        public virtual ЗАКАЗЧИКИ ЗАКАЗЧИКИ { get; set; }
        public virtual ТОВАРЫ ТОВАРЫ { get; set; }
    }
}
