//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗАКАЗЧИКИ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗАКАЗЧИКИ()
        {
            this.ЗАКАЗЫ = new HashSet<ЗАКАЗЫ>();
        }
    
        public string Наименование_фирмы { get; set; }
        public string Телефон { get; set; }
        public string Контактное_лицо { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗАКАЗЫ> ЗАКАЗЫ { get; set; }
    }
}
